name: gogohannah
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas>=2.3
      - python-dotenv>=1.2
      - openai>=2.15
      - rapidfuzz>=3.14
      - fastapi>=0.128
      - uvicorn>=0.40
      - python-multipart>=0.0.21
